const colors = {
  light: {
    text: "#EEEEFF",
    tint: "#7B61FF",
    background: "#0A0A0F",
    foreground: "#EEEEFF",
    card: "#13131A",
    cardForeground: "#EEEEFF",
    primary: "#7B61FF",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A2A",
    secondaryForeground: "#EEEEFF",
    muted: "#1E1E2A",
    mutedForeground: "#6B6B8E",
    accent: "#FF3C6E",
    accentForeground: "#FFFFFF",
    destructive: "#FF3C6E",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E2A",
    input: "#1E1E2A",
    // Pulzz brand extras
    discovered: "#7B61FF",
    discoveredGlow: "rgba(123, 97, 255, 0.3)",
    skip: "#FF3C6E",
    skipGlow: "rgba(255, 60, 110, 0.3)",
    surface: "#0D0D15",
    surfaceElevated: "#16161F",
  },
  dark: {
    text: "#EEEEFF",
    tint: "#7B61FF",
    background: "#0A0A0F",
    foreground: "#EEEEFF",
    card: "#13131A",
    cardForeground: "#EEEEFF",
    primary: "#7B61FF",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A2A",
    secondaryForeground: "#EEEEFF",
    muted: "#1E1E2A",
    mutedForeground: "#6B6B8E",
    accent: "#FF3C6E",
    accentForeground: "#FFFFFF",
    destructive: "#FF3C6E",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E2A",
    input: "#1E1E2A",
    discovered: "#7B61FF",
    discoveredGlow: "rgba(123, 97, 255, 0.3)",
    skip: "#FF3C6E",
    skipGlow: "rgba(255, 60, 110, 0.3)",
    surface: "#0D0D15",
    surfaceElevated: "#16161F",
  },
  radius: 12,
};

export default colors;
