uploads = []
outputs = []

[[generated]]
id = "F1dQ5ZrDDHG5z_sblk55-"
uri = "file://artifacts/pulzz-listener/assets/images/icon.png"
type = "image"
title = "pulzz app icon"

[[generated]]
id = "yv3IhOu4IPFsXekET8t1L"
uri = "file://artifacts/pulzz-listener/assets/images/splash.png"
type = "image"
title = "pulzz splash screen"

[[generated]]
id = "HUiE0f7mrZERuxkBJdVk1"
uri = "file://artifacts/pulzz-listener/assets/images/song-placeholder.png"
type = "image"
title = "song placeholder art"

[[generated]]
id = "HbObjUwwt8C9BSZeHimwA"
uri = "file://artifacts/api-server/public/media/art-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "MXrdpBaRRQj8DZzoaA7Wz"
uri = "file://artifacts/api-server/public/media/art-3.png"
type = "image"
title = "generated_image"
